# Generated by Django 5.2.15 on 2026-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
